import type { GrupoPruebaDefinition } from "../grupo-types";

// ============================================================
//  Grupos de pruebas — Convencional (TECDOC)
//
//  5 grupos (A–E). Los schemas de medición, fórmulas y criterios
//  se completan grupo por grupo conforme se construyen los formularios.
// ============================================================

const EMPTY_TEXTOS = { objetivo: "", instrumentacion: "", metodologia: "", criterio: "" };

/** Grupo A — Levantamiento Radiométrico e Inspección Visual */
const GRUPO_A: GrupoPruebaDefinition = {
  codigo: "a",
  nombre: "Levantamiento Radiométrico e Inspección Visual",
  orden: 1,
  schema_mediciones: { columnas: [] },
  slots_imagen: [],
  pruebas: [
    {
      codigo: "2.1",
      numero_tecdoc: "2.1",
      nombre: "Evaluación de las condiciones ambientales o levantamiento radiométrico",
      descripcion:
        "Elaboración de croquis de la sala con identificación de puntos de medición y registro de tasa de dosis",
      orden_en_grupo: 1,
      orden_global: 1,
      formulas: [],
      criterios_aceptacion: [],
      textos_informe: EMPTY_TEXTOS,
      slots_imagen: [],
    },
    {
      codigo: "2.2",
      numero_tecdoc: "2.2",
      nombre: "Inspección visual, descripción de la instalación y blindaje",
      descripcion: "Verificación visual del estado general de la sala y los blindajes",
      orden_en_grupo: 2,
      orden_global: 2,
      formulas: [],
      criterios_aceptacion: [],
      textos_informe: EMPTY_TEXTOS,
      slots_imagen: [],
    },
  ],
};

/** Grupo B — RaySafe: Tiempo, kVp, CHR, Rendimiento y Dosis */
const GRUPO_B: GrupoPruebaDefinition = {
  codigo: "b",
  nombre: "RaySafe: Tiempo, kVp, CHR, Rendimiento y Dosis",
  orden: 2,
  schema_mediciones: { columnas: [] },
  slots_imagen: [],
  pruebas: [
    {
      codigo: "2.4",
      numero_tecdoc: "2.4",
      nombre: "Exactitud y repetibilidad del tiempo de exposición",
      descripcion: "Compara el tiempo configurado vs el medido por el sensor RaySafe",
      orden_en_grupo: 1,
      orden_global: 3,
      formulas: [],
      criterios_aceptacion: [],
      textos_informe: EMPTY_TEXTOS,
      slots_imagen: [],
    },
    {
      codigo: "2.5",
      numero_tecdoc: "2.5",
      nombre: "Exactitud y repetibilidad de la tensión del tubo de rayos X",
      descripcion: "Compara el kVp configurado vs el medido por el sensor RaySafe",
      orden_en_grupo: 2,
      orden_global: 4,
      formulas: [],
      criterios_aceptacion: [],
      textos_informe: EMPTY_TEXTOS,
      slots_imagen: [],
    },
    {
      codigo: "2.6",
      numero_tecdoc: "2.6",
      nombre: "Capa hemirreductora (CHR)",
      descripcion: "Mide la calidad del haz — CHR debe superar el mínimo según el kV usado",
      orden_en_grupo: 3,
      orden_global: 5,
      formulas: [],
      criterios_aceptacion: [],
      textos_informe: EMPTY_TEXTOS,
      slots_imagen: [],
    },
    {
      codigo: "2.7",
      numero_tecdoc: "2.7",
      nombre: "Valor del rendimiento del tubo de rayos X, repetibilidad y linealidad",
      descripcion:
        "Cuánta radiación produce el tubo por cada mAs — debe ser consistente y lineal",
      orden_en_grupo: 4,
      orden_global: 6,
      formulas: [],
      criterios_aceptacion: [],
      textos_informe: EMPTY_TEXTOS,
      slots_imagen: [],
    },
    {
      codigo: "2.21",
      numero_tecdoc: "2.21",
      nombre: "Dosis al receptor de imagen",
      descripcion:
        "Mide cuánta radiación llega al detector con programas clínicos reales (con y sin rejilla)",
      orden_en_grupo: 5,
      orden_global: 7,
      formulas: [],
      criterios_aceptacion: [],
      textos_informe: EMPTY_TEXTOS,
      slots_imagen: [],
    },
    {
      codigo: "2.8",
      numero_tecdoc: "2.8",
      nombre: "Determinación del factor de corrección del producto kerma-área",
      descripcion: "Calcula el factor de corrección para el medidor de DAP del equipo",
      orden_en_grupo: 6,
      orden_global: 8,
      formulas: [],
      criterios_aceptacion: [],
      textos_informe: EMPTY_TEXTOS,
      slots_imagen: [],
    },
  ],
};

/** Grupo C — Control Automático de Exposición (CAE) — opcional */
const GRUPO_C: GrupoPruebaDefinition = {
  codigo: "c",
  nombre: "Control Automático de Exposición (CAE)",
  orden: 3,
  schema_mediciones: { columnas: [] },
  slots_imagen: [],
  pruebas: [
    {
      codigo: "2.17",
      numero_tecdoc: "2.17",
      nombre: "Sensibilidad del control automático de exposición (CAE)",
      descripcion:
        "Compara los valores del CAE con los de la visita anterior para verificar estabilidad",
      orden_en_grupo: 1,
      orden_global: 9,
      formulas: [],
      criterios_aceptacion: [],
      textos_informe: EMPTY_TEXTOS,
      slots_imagen: [],
    },
    {
      codigo: "2.18",
      numero_tecdoc: "2.18",
      nombre: "Consistencia entre los sensores del CAE",
      descripcion:
        "Verifica que los 3 sensores (izquierdo, centro, derecho) y sus combinaciones den resultados similares",
      orden_en_grupo: 2,
      orden_global: 10,
      formulas: [],
      criterios_aceptacion: [],
      textos_informe: EMPTY_TEXTOS,
      slots_imagen: [],
    },
    {
      codigo: "2.19",
      numero_tecdoc: "2.19",
      nombre: "Repetibilidad del CAE",
      descripcion: "Verifica que disparando varias veces con la misma configuración, el CAE da resultados consistentes",
      orden_en_grupo: 3,
      orden_global: 11,
      formulas: [],
      criterios_aceptacion: [],
      textos_informe: EMPTY_TEXTOS,
      slots_imagen: [],
    },
    {
      codigo: "2.20",
      numero_tecdoc: "2.20",
      nombre: "Compensación del CAE para diferentes valores de kVp y espesores",
      descripcion:
        "Verifica que el CAE ajusta correctamente al cambiar el voltaje o el grosor del paciente (simulado con cobre)",
      orden_en_grupo: 4,
      orden_global: 12,
      formulas: [],
      criterios_aceptacion: [],
      textos_informe: EMPTY_TEXTOS,
      slots_imagen: [],
    },
  ],
};

/** Grupo D — DDI/EI e Integridad CR */
const GRUPO_D: GrupoPruebaDefinition = {
  codigo: "d",
  nombre: "DDI/EI, Integridad y Uniformidad CR",
  orden: 4,
  schema_mediciones: { columnas: [] },
  slots_imagen: [],
  pruebas: [
    {
      codigo: "2.9",
      numero_tecdoc: "2.9",
      nombre: "Control de calidad del indicador de dosis digital (DDI) e índice de exposición (EI)",
      descripcion: "Verificación del DDI/EI del sistema",
      orden_en_grupo: 1,
      orden_global: 13,
      formulas: [],
      criterios_aceptacion: [],
      textos_informe: EMPTY_TEXTOS,
      slots_imagen: [],
    },
    {
      codigo: "2.10",
      numero_tecdoc: "2.10",
      nombre: "Repetibilidad del indicador de dosis digital (DDI) e índice de exposición (EI)",
      descripcion: "Verificación de la repetibilidad del DDI/EI",
      orden_en_grupo: 2,
      orden_global: 14,
      formulas: [],
      criterios_aceptacion: [],
      textos_informe: EMPTY_TEXTOS,
      slots_imagen: [],
    },
    {
      codigo: "2.14",
      numero_tecdoc: "2.14",
      nombre: "Integridad y limpieza de los cassettes y de las pantallas IP",
      descripcion: "Inspección visual de cassettes y pantallas",
      orden_en_grupo: 3,
      orden_global: 15,
      formulas: [],
      criterios_aceptacion: [],
      textos_informe: EMPTY_TEXTOS,
      slots_imagen: [],
    },
    {
      codigo: "2.15",
      numero_tecdoc: "2.15",
      nombre: "Uniformidad de la sensibilidad de las pantallas IP CR",
      descripcion: "Verificación de uniformidad de pantallas CR",
      orden_en_grupo: 4,
      orden_global: 16,
      formulas: [],
      criterios_aceptacion: [],
      textos_informe: EMPTY_TEXTOS,
      slots_imagen: [],
    },
  ],
};

/** Grupo E — Colimación, Resolución, Contraste y MTF */
const GRUPO_E: GrupoPruebaDefinition = {
  codigo: "e",
  nombre: "Colimación, Resolución, Contraste y MTF",
  orden: 5,
  schema_mediciones: { columnas: [] },
  slots_imagen: [],
  pruebas: [
    {
      codigo: "2.3",
      numero_tecdoc: "2.3",
      nombre: "Sistema de colimación del haz y perpendicularidad del rayo central",
      descripcion: "Evaluación de la colimación y alineación del haz",
      orden_en_grupo: 1,
      orden_global: 17,
      formulas: [],
      criterios_aceptacion: [],
      textos_informe: EMPTY_TEXTOS,
      slots_imagen: [],
    },
    {
      codigo: "2.11",
      numero_tecdoc: "2.11",
      nombre: "Uniformidad y artefactos del detector",
      descripcion: "Evaluación de uniformidad del detector y detección de artefactos",
      orden_en_grupo: 2,
      orden_global: 18,
      formulas: [],
      criterios_aceptacion: [],
      textos_informe: EMPTY_TEXTOS,
      slots_imagen: [],
    },
    {
      codigo: "2.12",
      numero_tecdoc: "2.12",
      nombre: "Resolución espacial de alto contraste",
      descripcion: "Determinación de la resolución espacial del sistema",
      orden_en_grupo: 3,
      orden_global: 19,
      formulas: [],
      criterios_aceptacion: [],
      textos_informe: EMPTY_TEXTOS,
      slots_imagen: [],
    },
    {
      codigo: "2.13",
      numero_tecdoc: "2.13",
      nombre: "Umbral de sensibilidad a bajo contraste",
      descripcion: "Evaluación de la sensibilidad a bajo contraste",
      orden_en_grupo: 4,
      orden_global: 20,
      formulas: [],
      criterios_aceptacion: [],
      textos_informe: EMPTY_TEXTOS,
      slots_imagen: [],
    },
    {
      codigo: "2.16",
      numero_tecdoc: "2.16",
      nombre: "Función de transferencia de modulación (MTF)",
      descripcion: "Evaluación de la MTF del sistema",
      orden_en_grupo: 5,
      orden_global: 21,
      formulas: [],
      criterios_aceptacion: [],
      textos_informe: EMPTY_TEXTOS,
      slots_imagen: [],
    },
  ],
};

export const GRUPOS_CONVENCIONAL: GrupoPruebaDefinition[] = [
  GRUPO_A,
  GRUPO_B,
  GRUPO_C,
  GRUPO_D,
  GRUPO_E,
];
