import type { ModuloVisita } from "../types";

export const MODULOS_CONVENCIONAL: ModuloVisita[] = [
  {
    id: "grupo-a",
    nombre: "Levantamiento Radiométrico e Inspección Visual",
    nombreCorto: "Levantamiento",
    icon: "Gauge",
    orden: 1,
    requerido: true,
    ruta: "conv/grupo-a",
  },
  {
    id: "grupo-b",
    nombre: "RaySafe: Tiempo, kVp, CHR, Rendimiento y Dosis",
    nombreCorto: "RaySafe",
    icon: "Zap",
    orden: 2,
    requerido: true,
    ruta: "conv/grupo-b",
  },
  {
    id: "grupo-c",
    nombre: "Control Automático de Exposición (CAE)",
    nombreCorto: "CAE",
    icon: "SlidersHorizontal",
    orden: 3,
    requerido: false,
    ruta: "conv/grupo-c",
  },
  {
    id: "grupo-d",
    nombre: "DDI/EI, Integridad y Uniformidad CR",
    nombreCorto: "DDI / CR",
    icon: "MonitorCheck",
    orden: 4,
    requerido: true,
    ruta: "conv/grupo-d",
  },
  {
    id: "grupo-e",
    nombre: "Colimación, Resolución, Contraste y MTF",
    nombreCorto: "Colimación",
    icon: "Target",
    orden: 5,
    requerido: true,
    ruta: "conv/grupo-e",
  },
  {
    id: "pre-informe",
    nombre: "Pre-Informe PDF",
    nombreCorto: "Pre-Informe",
    icon: "FileText",
    orden: 99,
    requerido: false,
    ruta: "pre-informe",
  },
];
